### ISSUE TITLE
0.1.3 Issue of UNKNOWN_ SOURCE still not fixed

### ISSUE THREAD

**Issue by starktony1** [5andr0/PogoLocationFeeder#161]
Hi 

    We are glad that you have released this new version of PogoLocation but Issue of Unknown Source is still not gone . Please FIX

**Comment by starktony1** [comment]
50% of The Channels are SPAM with wrong coordinates and saying to Snipe RATATA

**Comment by starktony1** [comment]
Why have you promoted Spamming Channels

**Comment by starktony1** [comment]
![image](https://cloud.githubusercontent.com/assets/20708547/17367212/c1957496-59ac-11e6-8f77-c0e68e6c95a7.png)

**Comment by 5andr0** [comment]
Filter coming. Spam is already filtered so relax. We are constantly adding and removing channels. Unknown Source should be fixed if you have the latest channels discord_channels.json

**Comment by ExcuseMi** [comment]
I also still have the unknow_source. I believe it's the pokesnipers integration

**Comment by luumanhvn** [comment]
damn it cant change discord_channels.json
f*** the UNKNOWN_ SOURCE

**Comment by djdookie** [comment]
Same here. I belive UNKNOWN_SOURCE comes from trackemon.

**Comment by Ilses** [comment]
I'll start looking into this now
