### ISSUE TITLE
Connection established waiting for data...

### ISSUE THREAD

**Issue by venenata** [5andr0/PogoLocationFeeder#217]
![image](https://cloud.githubusercontent.com/assets/20799950/17464695/477f96a0-5cb3-11e6-8808-9ef85d57c2c2.png)

how do i fix this

**Comment by NexLegend** [comment]
Nothing is wrong?

**Comment by 4rthurRousseau** [comment]
@venenata In your `config.json`, make sure that both `UsePokeSnipers` and `UseTrackemon` are set to `true`.

**Comment by bnmldn** [comment]
i've been having this issue all day on the GUI version. Config is fine. Doesn't pull any info through, just stays blank.

**Comment by 4rthurRousseau** [comment]
Does your `discord_channels.json` contains valid Discord channels?

**Comment by bnmldn** [comment]
I haven't modified mine `discord_channels.json` but when i looked through it i noticed it does contain valid channels

**Comment by Sylencer90** [comment]
Not working for me either

**Comment by bnmldn** [comment]
I assumed the update today on the wiki had something to do with it:

> UPDATE Aug. 7, 3:30 PM (GMT)
> We are aware that the feed seems to be down at the moment and are looking into the issue!

**Comment by 4rthurRousseau** [comment]
![pokesnipers](https://cloud.githubusercontent.com/assets/7251970/17465043/76931974-5cec-11e6-857d-449d7b43071e.png)

It's working here

**Comment by bnmldn** [comment]
@4rthurRousseau The CLI was working for me pulling data from Pokesnipers. The GUI is showing nothing at all, even with Pokesnipers and Trackemon set to `true`

**Comment by tensei** [comment]
gui is using the exact same logic and everything as cli so this doesn't make sense

**Comment by bnmldn** [comment]
@tensei i appreciate it doesn't make sense, but it doesn't work. The URL where the feed shows `404 Fuck You`.

I have sat with the GUI open all day, restarted several times and nothing changes, and no data shows.

**Comment by tensei** [comment]
if you look here its literally using the the program.cs from cli => [https://github.com/5andr0/PogoLocationFeeder/blob/master/PogoLocationFeeder.GUI/ViewModels/MainWindowViewModel.cs#L51](url)

**Comment by bnmldn** [comment]
I'm not sure why the GUI is showing nothing then. Also in watching the CLI gather data from Discord channels, its not pulling everything.

**Comment by tensei** [comment]
is this the latest?

**Comment by bnmldn** [comment]
Yes, using the [latest](https://github.com/5andr0/PogoLocationFeeder/releases).

When i open the GUI it recognises it is the latest version too.

**Comment by tensei** [comment]
.net framework 4.6.1 installed?
[https://www.microsoft.com/en-us/download/details.aspx?id=49981](url)

**Comment by weedorbeat** [comment]
Same here. Discord doesn't work for me too. .NET 4.6.1 is installed

**Comment by bnmldn** [comment]
@tensei yes, installed

@weedorbeat the GUI not working for you?

**Comment by weedorbeat** [comment]
Both does not work, console and GUI, when I only use Discord. If i use pokesniper, console and GUI work fine. But I want to use Discordonly. The days befor API changed its works great with Discord only.

**Comment by bnmldn** [comment]
Well something must have been fixed or worked itself out as now both the CLI and GUI are working for me. Bizarre

**Comment by weedorbeat** [comment]
Hm good for you, for me it still does not work.

[INFO] Connection established. Waiting for data...
[INFO] Connection established. Waiting for data...
[INFO] Connection established. Waiting for data...

everytime...

**Comment by bnmldn** [comment]
Yeah i had this all day myself, the configs were fine on both versions.

`[INFO]Connection established. Waiting for data...`

Not quite sure has gone here but before the GUI wouldn't work but the console would work intermittently. In the last 30 mins or so the CLI was working properly and now the GUI has decided to work as well. Wish i knew what happened, just hope you can get your problems resolved too.

**Comment by weedorbeat** [comment]
The same problem will be discussed in #203... i hope it will be fixed soon. I wish you a successful hunt ;)
